### ISSUE TITLE
Projeto de Interface

### ISSUE THREAD

**Issue by LuizFernandorf** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e2-proj-int-t8-aplicacao-de-rh-para-uma-empresa#3]

**Comment by lucasdamasceno96** [comment]
[wireframes.docx](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e2-proj-int-t8-aplicacao-de-rh-para-uma-empresa/files/9669737/wireframes.docx)

**Comment by lucasdamasceno96** [comment]
[wireframes.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e2-proj-int-t8-aplicacao-de-rh-para-uma-empresa/files/9669755/wireframes.pdf)
