### ISSUE TITLE
Plano de Testes de Software

### ISSUE THREAD

**Issue by LuizFernandorf** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e2-proj-int-t8-aplicacao-de-rh-para-uma-empresa#8]

**Comment by lucasdamasceno96** [comment]
<span style="color:red">Pré-requisitos: <a href="2-Especificação do Projeto.md"> Especificação do Projeto</a></span>, <a href="3-Projeto de Interface.md"> Projeto de Interface</a>

**Os requisitos para realização dos testes de software são:<br> 
    - Site publicado na Internet <br> 
    - Navegador da Internet - Chrome <br> 
    - Conectividade de Internet para acesso às plataformas** <br> 

Os testes funcionais a serem realizados no aplicativo são descritos a seguir.


Por exemplo:

| **Caso de Teste** 	| **CT-01 – Visualizar pagina inicial** 	|
|:---:	|:---:	|
|	Requisito Associado 	|RF-01 - Na página principal do site deve exigir login e senha para que o usuário tenha acesso ao sistema. |
| Objetivo do Teste 	| Verificar se o sistema de login e senha estao funcionando corretamentes |
| Passos 	| - 1. Acessar o navegador <br> 2.Informar o endereço do Site <br> 3.Visualizar a página principal <br> 4. Acessar com login e senha 
|Critério de Êxito | - Login e senha devem ser executados sem erro. |
|  	|  	|
| **Caso de Teste**	| **CT-02 – Pagina de registro de pontos**	|
|Requisito Associado | O site deve deve ter página de registro de pontos, onde usuário poderá registrar o início e fim da jornada de trabalho|
| Objetivo do Teste 	| Verificar se os registros estao sendo executados corretamente conforme horario de brasilia e salvo no banco de dados |
| Passos 	| 1. Acessar o navegador <br> 2.Informar o endereço do Site <br> 3.Visualizar a página principal <br> 4. Acessar com login e senha <br> 5. Acesar pagina de registro de pontos e fazer o registro |
|Critério de Êxito | - Registro salvo com sucesso conforme horario de brasilia |


 
> **Links Úteis**:
> - [IBM - Criação e Geração de Planos de Teste](https://www.ibm.com/developerworks/br/local/rational/criacao_geracao_planos_testes_software/index.html)
> - [Práticas e Técnicas de Testes Ágeis](http://assiste.serpro.gov.br/serproagil/Apresenta/slides.pdf)
> -  [Teste de Software: Conceitos e tipos de testes](https://blog.onedaytesting.com.br/teste-de-software/)
> - [Criação e Geração de Planos de Teste de Software](https://www.ibm.com/developerworks/br/local/rational/criacao_geracao_planos_testes_software/index.html)
> - [Ferramentas de Test para Java Script](https://geekflare.com/javascript-unit-testing/)
> - [UX Tools](https://uxdesign.cc/ux-user-research-and-user-testing-tools-2d339d379dc7)
